interface lang {
        work_left_theme:string,
        work_left_lang:string,
        work_left_exit:string,
        today:string,
        nextSevenDays:string,
        all:string,
        myList:string,
        completed:string,
        trash:string,
        search:string,
        hiddenSearch:string,
        addTask:string,
        add_task_wind_title:string,
        add_task_wind_tag:string,
        add_task_wind_btnTag:string,
        add_task_wind_addColor:string,
        add_task_wind_description:string,
        add_task_wind_btnAdd:string,
        change_task_wind_title:string,
        change_task_wind_tag:string,
        change_task_wind_date:string,
        change_task_wind_color:string,
        change_task_wind_description:string,
        change_task_wind_descriptionPlacehold:string,
        change_task_wind_deleted_title:string,
        change_task_wind_deleted_OK:string,
        change_task_wind_deleted_NO:string,
}
export const eng:lang = {
        work_left_theme:'Theme',
        work_left_lang:'Lang',
        work_left_exit:'Exit',
        today:'Today',
        nextSevenDays:'Next 7 days',
        all:'All',
        myList:'My List',
        completed:'Completed',
        trash:'Trash',
        search:'Search',
        hiddenSearch:'Search',
        addTask:'Add Task',
        add_task_wind_title:'Add title',
        add_task_wind_tag:'Add Tag',
        add_task_wind_btnTag: 'Tags:',
        add_task_wind_addColor:'Add color:',
        add_task_wind_description:'Add description',
        add_task_wind_btnAdd:'Add',
        change_task_wind_title:'Title:',
        change_task_wind_tag:'Tag:',
        change_task_wind_date:'Date',
        change_task_wind_color:'Color:',
        change_task_wind_description:'Description:',
        change_task_wind_descriptionPlacehold:'Text',
        change_task_wind_deleted_title:'Delete task?',
        change_task_wind_deleted_OK:'Delete',
        change_task_wind_deleted_NO:'Cancel',
}