interface lang {
        work_left_theme:string,
        work_left_lang:string,
        work_left_exit:string,
        today:string,
        nextSevenDays:string,
        all:string,
        myList:string,
        completed:string,
        trash:string,
        search:string,
        hiddenSearch:string,
        addTask:string,
        add_task_wind_title:string,
        add_task_wind_tag:string,
        add_task_wind_btnTag:string,
        add_task_wind_addColor:string,
        add_task_wind_description:string,
        add_task_wind_btnAdd:string,
        change_task_wind_title:string,
        change_task_wind_tag:string,
        change_task_wind_date:string,
        change_task_wind_color:string,
        change_task_wind_description:string,
        change_task_wind_descriptionPlacehold:string,
        change_task_wind_deleted_title:string,
        change_task_wind_deleted_OK:string,
        change_task_wind_deleted_NO:string,
}
export const russ:lang = {
        work_left_theme:'Тема',
        work_left_lang:'Язык',
        work_left_exit:'Выход',
        today:'Сегодня',
        nextSevenDays:'7 дней',
        all:'Все',
        myList:'Мои темы',
        completed:'Выполнено',
        trash:'Просрочено',
        search:'Результат поиска',
        hiddenSearch:'Поиск',
        addTask:'Добавить запись',
        add_task_wind_title:'Введите заголовок',
        add_task_wind_tag:'Введите тему',
        add_task_wind_btnTag: 'Темы:',
        add_task_wind_addColor:'Выберете цвет:',
        add_task_wind_description:'Описание',
        add_task_wind_btnAdd:'Добавить',
        change_task_wind_title:'Заголовок:',
        change_task_wind_tag:'Тема:',
        change_task_wind_date:'Дата:',
        change_task_wind_color:'Цвет:',
        change_task_wind_description:'Описание:',
        change_task_wind_descriptionPlacehold:'Текст',
        change_task_wind_deleted_title:'Удалить запись?',
        change_task_wind_deleted_OK:'Удалить',
        change_task_wind_deleted_NO:'Отмена',
}